# Generated by Django 5.1.3 on 2024-12-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=50)),
                ('CarName', models.CharField(max_length=50)),
                ('CarPrice', models.IntegerField()),
                ('Company', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Cars Data',
            },
        ),
    ]
